# Generated by Django 5.2 on 2025-05-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_uu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descripition',
            new_name='description',
        ),
    ]
