# Generated by Django 5.2 on 2025-05-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movielist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielist',
            old_name='movie',
            new_name='movie_set',
        ),
    ]
