# Generated by Django 5.2 on 2025-05-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_movie_movielist_movie_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielist',
            old_name='movie_set',
            new_name='movie',
        ),
    ]
